### ISSUE TITLE
`yarn add` fails at flowgen step

### ISSUE THREAD

**Issue by x-ji** [marlenecota/react-native-svg#29]
Thanks a lot for porting this library to Windows. I'm trying to test it in my project with `yarn add https://github.com/marlenecota/react-native-svg#windows-pr`. The package fetching finished fine, however, the process failed at the end with:

```
[4/4] Building fresh packages...
success Saved lockfile.
$ npm run flowgen && npm run bob

> react-native-svg@12.2.0 flowgen
> flowgen src/index.d.ts -o src/index.js.flow

C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\printers\node.js:128
        const decl = leftMostSymbol && leftMostSymbol.declarations.length ? leftMostSymbol.declarations[0] : {};
                                                                   ^

TypeError: Cannot read properties of undefined (reading 'length')
    at getFullyQualifiedName (C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\printers\node.js:128:68)
    at C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\printers\node.js:521:41
    at fn (C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\env.js:10:12)
    at Array.map (<anonymous>)
    at C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\printers\node.js:609:27
    at Object.fn (C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\env.js:10:12)
    at Object.typeDeclaration (C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\printers\declarations.js:222:110)
    at Property.print (C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\nodes\property.js:85:38)
    at C:\Users\jx\AppData\Local\Yarn\Cache\v6\.tmp\118abef8f903599b963eefe88b89d4ba.544519fb2a7374d9139b3398bf0557e4ee67616a.prepare\node_modules\flowgen\lib\cli\compiler.js:35:18
    at Array.map (<anonymous>)
error Command failed with exit code 1.
```

Maybe I'm doing something wrong here.

**Comment by BryanRolfe** [comment]
Any updates on this issue? I'm seeing this as well and have had no luck resolving it
